# Generated by Django 5.2.2 on 2025-06-25 01:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.IntegerField(default=0)),
                ('telefono', models.CharField(default=0, max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoCXC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoCXP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermisoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('gerente', models.BooleanField(default=False)),
                ('sprempleado', models.BooleanField(default=False)),
                ('empleado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.IntegerField(default=0)),
                ('telefono', models.CharField(default=0, max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('n_cxc', models.AutoField(primary_key=True, serialize=False)),
                ('conceptoDetalle', models.TextField(blank=True, null=True)),
                ('val_bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('neto_facturado', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('abonos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pendiente_por_pagar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_modfinanciero.cliente')),
                ('conceptoFijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_modfinanciero.conceptocxc')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoResultadosMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('ingresos_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('costos_operacion_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilidad_bruta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gastos_administrativos_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilidad_operacional', models.DecimalField(decimal_places=2, max_digits=15)),
                ('otros_costos_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilidad_antes_impuestos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gastos_impuestos', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilidad_neta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ingresos_detalle', models.JSONField(default=dict)),
                ('costos_operacion_detalle', models.JSONField(default=dict)),
                ('gastos_administrativos_detalle', models.JSONField(default=dict)),
                ('otros_costos_detalle', models.JSONField(default=dict)),
                ('impuestos_detalle', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estado de Resultados Mensual',
                'verbose_name_plural': 'Estados de Resultados Mensuales',
                'unique_together': {('anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notacredito', to='backend_modfinanciero.cuentaporcobrar')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.IntegerField(default=0)),
                ('telefono', models.CharField(default=0, max_length=20)),
                ('perfiles', models.ManyToManyField(blank=True, to='backend_modfinanciero.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('n_cxp', models.AutoField(primary_key=True, serialize=False)),
                ('conceptoDetalle', models.TextField(default=1)),
                ('val_bruto', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=15)),
                ('abonos', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('pendiente_por_pagar', models.DecimalField(decimal_places=2, max_digits=15)),
                ('conceptoFijo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_modfinanciero.conceptocxp')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_modfinanciero.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_modfinanciero.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=254, null=True)),
                ('token_recuperar', models.CharField(default='sin cambios pendientes ', max_length=254)),
                ('telefono', models.CharField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('rol', models.IntegerField(choices=[(1, 'admin'), (2, 'gerente'), (3, 'sprempleado'), (4, 'empleado')], default=4)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_modfinanciero.tienda')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
