# Generated by Django 5.2.2 on 2025-06-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_modfinanciero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_modfinanciero.cliente'),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_modfinanciero.proveedor'),
        ),
    ]
