# Generated by Django 5.2.2 on 2025-06-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_modfinanciero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
