# Generated by Django 5.2.2 on 2025-06-10 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
