# Generated by Django 5.2.2 on 2025-06-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token_recuperar',
            field=models.CharField(default='sin cambios pendientes', max_length=254),
        ),
    ]
