# Generated by Django 5.2.2 on 2025-06-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0002_alter_usuario_token_recuperar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'administrador'), (2, 'gerente'), (3, 'sprEmpleado'), (4, 'empleado')], default=4),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token_recuperar',
            field=models.CharField(default='sin cambios pendientes ', max_length=254),
        ),
    ]
