# Generated by Django 5.2.2 on 2025-06-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0003_alter_usuario_rol_alter_usuario_token_recuperar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'gerente'), (3, 'sprempleado'), (4, 'empleado')], default=4),
        ),
    ]
