# Generated by Django 5.2.2 on 2025-06-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0004_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100, unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('gerente', models.BooleanField(default=False)),
                ('sprempleado', models.BooleanField(default=False)),
                ('empleado', models.BooleanField(default=False)),
            ],
        ),
    ]
