# Generated by Django 5.2.2 on 2025-06-11 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0004_usuario_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='cantidad_empleados',
        ),
    ]
