# Generated by Django 5.2.2 on 2025-06-17 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0006_conceptocxc_conceptocxp_cuentaporcobrar_conceptofijo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentaporcobrar',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='cuentaporpagar',
            name='neto_facturado',
        ),
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='conceptoDetalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='conceptoDetalle',
            field=models.TextField(default=1),
        ),
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='conceptoFijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_financiero.conceptocxc'),
        ),
        migrations.AlterField(
            model_name='cuentaporpagar',
            name='conceptoFijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='modulo_financiero.conceptocxp'),
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito', to='modulo_financiero.cuentaporcobrar')),
            ],
        ),
    ]
