# Generated by Django 5.2.2 on 2025-06-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0007_remove_cuentaporcobrar_concepto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='val_bruto',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
