# Generated by Django 5.2.2 on 2025-06-18 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0008_alter_cuentaporcobrar_val_bruto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacredito',
            name='cuenta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notacredito', to='modulo_financiero.cuentaporcobrar'),
        ),
    ]
