# Generated by Django 5.2.2 on 2025-06-18 01:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0009_alter_notacredito_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoResultadosMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('ingresos_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('costos_operacion_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilidad_bruta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gastos_administrativos_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilidad_operacional', models.DecimalField(decimal_places=2, max_digits=15)),
                ('otros_costos_total', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilidad_antes_impuestos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gastos_impuestos', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilidad_neta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ingresos_detalle', models.JSONField(default=dict)),
                ('costos_operacion_detalle', models.JSONField(default=dict)),
                ('gastos_administrativos_detalle', models.JSONField(default=dict)),
                ('otros_costos_detalle', models.JSONField(default=dict)),
                ('impuestos_detalle', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Estado de Resultados Mensual',
                'verbose_name_plural': 'Estados de Resultados Mensuales',
                'unique_together': {('anio', 'mes')},
            },
        ),
    ]
