# Generated by Django 5.2.2 on 2025-06-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0010_estadoresultadosmensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default=0),
        ),
    ]
