# Generated by Django 5.2.2 on 2025-06-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0011_alter_usuario_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentaporcobrar',
            name='abonos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
