# Generated by Django 5.2.2 on 2025-06-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_financiero', '0012_alter_cuentaporcobrar_abonos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadoresultadosmensual',
            name='creado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
